"use strict";
var errors = {
	"invalid_parameters" 										: [100, "Invalid Parameters"],
	"server_error"		 										: [500, "Something went wrong"],
	"no_server_response"										: [2300,"No response from server"],
	"invalid_email"												: [101, "Invalid Email Id"],
	"user_already_exists"										: [102, "User email already exists"],
	"otp_error"			 										: [300,"OTP submitted is invaid."],
	"page_not_found"											: [404,"Sorry! Page not found"],
	"account_not_found"											: [404,"Account was not found."],
	"profile_not_found"											: [404,"Profile was not found."],
	"unable_to_update"											: [500,"Unable to update right now, please try after some time"],
	"phone_number_not_found"									: [404,"Phone number was not found."],
	"account_already_exists"									: [409,"Account already exists."],
	"profile_already_exists"									: [409,"Profile already exists."],
    "account_not_verified"										: [700,"Account not verified yet."],
	"invalid_type_of_password"									: [400,"Password must be string"],
	"short_password"        									: [400,"Please enter a password at least 6 characters long"],
	"incorrect_old_password"    								: [400,"Old password is incorrect"],
	"incorrect_password"    									: [400,"Password you enter is incorrect"],
	"password_not_match"    									: [400,"Password not match"],
	"verify_email"		           								: [34000, "Please verify your email"],
	"verify_account_first"										: [401, "Please verify your account first"],
	"phone_number_already_exists"								: [400,"Phone number already exist"],
	"invalid_url"												: [400,"Invalid url"],
	"email_alredy_taken"										: [400,"This email is alredy linked with another account"],
	"email_required"											: [400,"Email is required"],
	"invalid_phone_number"										: [400,"Invalid phone number"],
	"invalid_permission"										: [400,"Invalid permisson"],
	"invalid_permission_status"									: [400,"Invalid permisson status"],
	"skills_required"											: [400,"Please enter valid skills, skills is required"],
	"skill_not_found"										    : [404,"Skill not found"],
	"jwt_verify_error"											: [500,"JWT verify error "],
	"jwt_token_expired"											: [498,"JWT token expired"],
	"jwt_token_not_found"										: [403,"JWT Token not found"],
	"unauthorised"												: [401,"You are not authorised"],
	"candidate_blacklisted"										: [40300,"You are blacklisted by admin please contact admin"],
	"mongo_error"												: [500,"Mongo error !"],
	"unable_to_update"										    : [500,"Unable to update please try after some time"],
	"org_not_found"											    : [404,"Organisation not found"],
	"verify_organisation"										: [40400, "Please verify organisation"],
	"organisation_rejected"										: [40100, "Organisation Rejected"],
	"no_org_create_already_in_org"								: [500,"Sorry you can not create organisation because you are alredy a part of an organisation"],
	"org_name_required"											: [400,"Organisation name is required"],
	"org_logo_required"											: [400,"Organisation logo is required"],
	"org_url_required"											: [400,"Organisation url is required"],
	"org_site_must_url"										    : [400,"Organisation site must be a url"],
	"org_logo_must_url"										    : [400,"Organisation logo must be a url"],
	"not_authorised"										    : [403,"You are not authorised"],
	"start_month_required"										: [400,"Start month is required"],
	"start_year_required"										: [400,"Start year is required"],
	"invalid_start_month"										: [400,"Start month is invalid"],
	"invalid_start_year"										: [400,"Start year is invalid"],
	"end_month_required"										: [400,"End month is required"],
	"end_year_required"				    						: [400,"End year is required"],
	"invalid_end_month"			    							: [400,"End month is invalid"],
	"invalid_end_year"			    							: [400,"End year is invalid"],
	"start_date_greater_then_end_date"			    			: [400,"Start date can't be greater then end date"],
	"start_date_cant_in_future"     			    			: [400,"Start date can't be in future"],
	"reach_max_skill_limit"										: [400,"Sorry!, You reach maximum skill limit"],
	"job_not_found"	    									    : [404,"Job not found"],
	"candidate_application_not_found"	    					: [404,"Candidate application not found"],
	"not_panding_candidate_apl"              					: [500,"This candidate application is not in pending state"],
	"not_shortlist_candidate_apl"            					: [500,"This candidate application is not in shortlist state"],
	"not_hire_candidate_apl"     	           					: [500,"This candidate application is not in hired state"],
	"cant_do_action_candidate_after_hired"      				: [500,"This candidate is alredy hired you can not change this action"],
	"file_not_found"	    									: [404,"File not found"],
	"invalid_file_type"											: [400,"File type is invalid"],
	"invalid_action"											: [400,"The action you are going to perform is invalid or expired"],
	"insufficient_reject_reason"								: [400,"Sufficient reject reason is required"]
};

module.exports = errors; 